### ISSUE TITLE
Consider if some/all commands should support working with multiple files

### ISSUE THREAD

**Issue by mandx** [braver/SideBarTools#11]
Following [discussion from an earlier PR](https://github.com/braver/SideBarTools/pull/9#issuecomment-320521222):

> Well, perhaps if `paths` > 1, you could ask for a target directory and move everything there?

I think this feature is not about code, we know how to easily move/copy files. This is about UI/UX, how to achieve what the user expects, with the minimum amount of clicks/steps and with the minimal interface SublimeText provides.

My intention with this ticket is to discuss here if this is possible and how to do it, then more issues could be created to cover the implementation of the subtasks for this "meta"-feature.

As a consequence, another option is to not support handling multiple files at all.

**Comment by braver** [comment]
> As a consequence, another option is to not support handling multiple files at all.

I don't think that is a bad option at all. At some point you're simply better off going to the command line or a file manager. I've been using Sublime since around 2011 and only recently found out you can select multiple files in the sidebar. Perhaps I'm dense, but I also feel Sublime is at its best when it sticks to its core competencies and doesn't try to also be a file manager and a git GUI and etc etc.

However we already have no support, so that's boring. Let's consider the options.

- Copy Filename
- Copy Relative Path
- Copy Absolute Path

In these cases it would make sense to make a list and separate the paths with newlines. Seems easy enough.

- Duplicate

Your selection can include things located anywhere on the file system. Right now, duplicate creates a new file/folder next to the original, and lets you choose its name. For multiple paths you could ask the user for input on every single one of them. However, I think it will be quite hard to understand the order and progress of such a process and it might not be easy to distinguish between files (say you have 4 index.html files in different locations you want to duplicatie). It might not be feasible to display the full path of the original in all cases. Lacking a fancy UI to handle this task I would be better to ask for input only once. Perhaps the easiest to understand would be to ask for a suffix (e.g. " (Copy)"). A more powerful option would be to do a pattern replacement like you would use shell parameter expansion for `cp` or `mv` in bash. You could ask for a `/pattern/string`.

- Move

This has similar problems as Duplicate. Again I don't think we should deal with this one path at a time, but as a single operation. I see two options, and perhaps we should have both:

- Move selected files/folder into one folder (i.e. "collect" them)  
Ask the user for a target directory and move everything there. Example (`[]` indicates selection):


```
[file.a]            | 
[folderX]           |  
folderY/            | 
    [file.c]        |  
target directory/   |   target directory/
                    |       file.a     
                    |       folderX     
                    |       file.c 
```

I'm not sure what would happen if the target directory is inside folderX (i.e. a directory that's in the selection). Perhaps we should just check for that, throw a message and cancel.

- Pattern rename each file/folder  
As with duplication, ask for a `/pattern/string` and do what `mv` would do. 


-----------

A common theme here is how to deal with collision. There is no good way (in Sublime) to interactively resolve this and there is also no good way I know of to select a strategy (e.g. overwrite, rename, cancel) beforehand. This is where Sublime comes up short compared to Explorer/Finder and the major reason for me to be hesitant about batch duplicate/move. It becomes this clumsy proxy for a command line, and if you know how pattern replacement works there why not just go to that command line for such operations.

**Comment by mandx** [comment]
For clipboard related operations, I think is clear that we can easily support handling multiple files. Now, for move/duplicate, there's a difference in behavior compared to traditional file managers, that this plugin you choose destination *and* name ("dirname" and "basename"), as opposed to traditional file managers, where you only choose a new destination ("dirname") and the "basename" is preserved.

**Comment by braver** [comment]
> that this plugin you choose destination and name ("dirname" and "basename")

Well, I would propose that if you have multiple paths selected, you wouldn't get the Move command, but a Collect command, which only takes a "dirname" (and will "collect" all selected entities into a single directory). So, if in that case the "basenames" *would* be preserved.

**Comment by mandx** [comment]
I have added a PR (#14) that will address the clipboard-related commands. Now we can focus this discussion on the rest of the commands.

**Comment by braver** [comment]
I don't think there is sufficient demand for file operations with multiple files. I also feel like it's less easy to predict from the user's point of view how the tool will deal with that. So, while I think we can do something nice here, it just doesn't feel like something a lot of people will use. If I'm wrong I'm sure the feature request will pop up again by itself and we'll have this discussion to refer to. For now though, I'm closing the issue.
