### ISSUE TITLE
Feature Request: move file/folder

### ISSUE THREAD

**Issue by unknownuser88** [braver/SideBarTools#5]
Hi there.

I was hugely excited to find your plugin

it would be nice to have move (file/folder) function in sidebar that I use a lot

**Comment by braver** [comment]
@unknownuser88 I'm glad you're happy with the plugin. I generally use the built-in `Rename` feature to move files and folders. Would that work for you?

**Comment by unknownuser88** [comment]
Not quite 
rename put in input only file name but it should put all path for easy move
it work for me too but it difficult to move file to 2 level up and put in other folder
![screenshot from 2017-06-29 16-14-00](https://user-images.githubusercontent.com/2427559/27687045-5724c16e-5ce6-11e7-8023-3101c6ad3f0b.png)

**Comment by braver** [comment]
You can rename to `../../helper.js` and it will move two folders up. It's a bit tricky, but it does the job unless you need to really move it somewhere else entirely.

**Comment by braver** [comment]
rename also accepts absolute paths, so... I'm not sure I'll be able to improve on that in a significant way

**Comment by mandx** [comment]
First of all, thanks for creating the fork I was going to create after learning today about the original plugin tracking its users.

Now, I'm more used to use 'Move' (even for renaming operations) because it gives me context on the file I'm moving/renaming, I can see the full file's path (relative to the project's root), so I can decide right there if I want to leave it in the same folder with a different name or move it to another folder, with the same or different name.

Relative path works, but every time I would have to go and recheck the sidebar tree, using the mouse, to confirm that I got the `..` count right. It is easier to decide if I can see the current dirname/basename right there in one box, and tweak it using the keyboard.

**Comment by braver** [comment]
@mandx alright, that sounds like a good reason to add a “native” move action. Would also make it more discoverable. Anyone wants to open a PR with a project-relative-path-move feature is welcome.

**Comment by mandx** [comment]
In any case, I do appreciate the discussion on why this is needed. One of the things that annoys me about the original plugin is the amount of actions available (and sometimes with redundant/ambiguous meanings).

I may have time for a PR later in the day.

**Comment by braver** [comment]
> One of the things that annoys me about the original plugin is the amount of actions available 

Indeed. I would like for this to stay focused and tiny. I don’t need to copy a file path in 5 different encodings and what not.

**Comment by facelessuser** [comment]
Also think move will be a great option as well.  In general I like that it's keeping to the basics.  I also was annoyed at how large the **other** plugin's menu were.  This is a good example of why sometimes its nice to have alternatives on Package Control. Also like the "we won't track you ever" feature as well 🙂 .

Good job. Saved me from having to throw this together myself.
